author: "[[ê¹€ì„ ìŒ]]"

folders:
  inbox: "ğŸ“¥ Inbox"
  quick: "ğŸ“¥ Inbox/_quick"
  webclip: "ğŸ“¥ Inbox/_webclip"
  projects: "ğŸ¯ Projects"
  areas: "ğŸ”„ Areas"
  resources: "ğŸ“š Resources"
  archive: "ğŸ—ƒï¸ Archive"
  zettel: "ğŸ’ Zettel"
  meta: "âš™ï¸ Meta"
  templates: "âš™ï¸ Meta/Templates"
  daily: "ğŸ”„ Areas/Daily"

cmds_stages:
  - inbox
  - connect
  - merge
  - develop
  - share

status_levels:
  - seed
  - sapling
  - evergreen
  - archive

domains:
  - cs
  - ee
  - phil
  - math
  - robotics
  - general

prefixes:
  daily: "D"
  lecture: "L"
  concept: "C"
  problem: "P"
  reference: "R"
  meeting: "MTG"
  project: "PRJ"
  zettel: "Z"
  question: "Q"
